/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 SP2.3
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "NOKIA5110_display.h"
#include "NOKIA5110_bitmap.h"
#include "NOKIA5110_fonts.h"
#include "DN_aliases.h"
#include "DN.h"
#include "Pin_2_aliases.h"
#include "Pin_2.h"
#include "clk.h"
#include "SCLK_aliases.h"
#include "SCLK.h"
#include "CE_aliases.h"
#include "CE.h"
#include "RST_aliases.h"
#include "RST.h"
#include "DC_aliases.h"
#include "DC.h"
#include "NOKIA5110_SPI.h"
#include "NOKIA5110_SPI_PVT.h"
#include "NOKIA5110_Control.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

